# Generated by Django 6.0.2 on 2026-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_purchases',
            field=models.IntegerField(default=0, help_text='Total number of items purchased'),
        ),
    ]
