# Generated by Django 6.0.2 on 2026-02-20 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_laptops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestNewLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(help_text='Laptop model/name you want', max_length=200)),
                ('specifications', models.TextField(help_text='Specifications you need (processor, RAM, storage, etc.)')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Your budget in your local currency', max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_details', models.TextField(blank=True, help_text='Any other details or preferences')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Owner Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('owner_notes', models.TextField(blank=True, help_text='Notes from shop owner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'New Laptop Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
