# Generated by Django 6.0.1 on 2026-02-23 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_laptops', '0002_requestnewlaptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestnewlaptop',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='requestnewlaptop',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='requestnewlaptop',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='requestnewlaptop',
            name='specifications',
        ),
        migrations.AddField(
            model_name='requestnewlaptop',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='requestnewlaptop',
            name='laptop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_laptops.category'),
        ),
        migrations.AddField(
            model_name='requestnewlaptop',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='requestnewlaptop',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
