# Generated by Django 6.0.1 on 2026-02-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_laptops', '0003_remove_requestnewlaptop_additional_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Laptop Categories',
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='requestnewlaptop',
            name='laptop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_laptops.laptopcategory'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
