# Generated by Django 6.0.1 on 2026-03-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
    ]
